# Generated by Django 4.0 on 2021-12-29 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='Registration',
        ),
    ]
